### **numpy Array oprations**

In [6]:
import numpy as np

In [9]:
#--slicing

arr = np.array([1,2,3,4,5,6,7,8,9])
print("slicing  :",arr[2:7])
print("with step :",arr[2:7:2])
print("Negative indexing :",arr[-4])

slicing  : [3 4 5 6 7]
with step : [3 5 7]
Negative indexing : 6


In [46]:
arr_2d = np.array([[1,2,3],  #----- oth row
                   [4,5,6],  #----- 1st row
                   [7,8,9]]) #----- 2nd row
print(" Specific element  :",(arr_2d[1,2]))
print("Entire row :",arr_2d[1])
print("Entire column :",arr_2d[:,1])

 Specific element  : 6
Entire row : [4 5 6]
Entire column : [2 5 8]


### **Sorting**

In [16]:
unsorted = np.array([2,4,5,9,1,2,6,8])
print("sorted arr :",np.sort(unsorted))

arr_2d_sorted =np.array([[3,1],[1,2],[2,3]])
print("sorted 2d array by column :",np.sort(arr_2d_sorted,axis=0))
print("sorted 2d array by row :",np.sort(arr_2d_sorted,axis=1))

sorted arr : [1 2 2 4 5 6 8 9]
sorted 2d array by column : [[1 1]
 [2 2]
 [3 3]]
sorted 2d array by row : [[1 3]
 [1 2]
 [2 3]]


### ***Filter***

In [17]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
even_numbers = numbers%2 == 0
print("even numbers :",numbers[even_numbers])

even numbers : [2 4 6 8]


### **Filter with mask**

In [18]:
mask = numbers>5
print("numbers greater than five",numbers[mask])

numbers greater than five [6 7 8 9]


### **Fancy indexing vs np.where()**

In [26]:
indices = [1,4,7]   #--- through indexing
print(numbers[indices])

where_result = np.where(numbers>5)   #-----through np.where
print("np Where :",numbers[where_result])

[2 5 8]
np Where : [6 7 8 9]


In [32]:
condition_array = np.where(numbers>5,"true","false")    ##--------- its like if elsefirst section for condition like numbers>5 and second for if fist condition is true then second section will be exucuted otherwise for false condition last section will be exicuted
print(condition_array)
condition_array = np.where(numbers>5,numbers*2,"false")
print(condition_array)


['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true']
['false' 'false' 'false' 'false' 'false' '12' '14' '16' '18']


### **Adding and removing data**

In [33]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6,])
combine = np.concatenate((arr1,arr2))
print("combineing arr1and arrr2\n",combine)

combineing arr1and arrr2
 [1 2 3 4 5 6]


### **Array compatibility**

In [39]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,4])
print("compatibility shape :",a.shape == b.shape)
print("compatibility shape :",a.shape == c.shape)

compatibility shape : True
compatibility shape : False


In [43]:
original = np.array([[1,2,],[3,4]])
new_row =np.array([5,6])
with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)

new_col = np.array([[6],[9]])
with_new_col = np.hstack((original,new_col))
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 6]
 [3 4 9]]


In [56]:
arr = np.array([1,2,3,4,5,6])
deleted = np.delete(arr,4)
print("array after deletion",deleted)




array after deletion [1 2 3 4 6]
