In [ ]:
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
#Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print(" ==: zomzto sales analysis :==")
print("\n sales data shape",np.shape(sales_data))
print("\n first 3 resturent data",sales_data[:3])

 ==: zomzto sales analysis :==

 sales data shape (5, 5)

 first 3 resturent data [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [ ]:
# Total sales per year
print("total sales per year := \n",np.sum(sales_data,axis=0))
yearly_total=np.sum(sales_data[:,1:],axis=0)
print("year_total  :==\n",yearly_total)
total = np.sum(yearly_total)
print("total sales :==\n",total)

# MINIMUM sales per resturent
min_sales = np.min(sales_data[:,1:],axis=1)
print("minimum sales per resturent :==\n",min_sales)


#MAXIMUM sales per year
max_year_sales =np.max(sales_data[:,1:],axis=0)
print("maximum sales per year :==\n",max_year_sales)

#Average sales per restaurent
avg_sales = np.mean(sales_data[:,1:],axis=1)
print("average sales per restaurent :==\n",avg_sales)

#Average sales per year
avg_year = np.mean(sales_data[:,1:],axis=0)
print("average sales per year ;=\n",avg_year)


"""
 note is that in axis=0 = column and axis =1= rows-- and by default is 0
 but in function[x,y] then x= rows and y=clmns
 """


cumulative_sales = np.cumsum(sales_data[:,1:],axis=0)
print("cumulative sales :==\n",cumulative_sales)

plt.figure(figsize=(10, 6))
plt.plot(np.mean(cumulative_sales,axis=0))
plt.title("Cumulative Sales Over Years")
plt.xlabel("Year")
plt.ylabel("Cumulative Sales")
plt.grid(True)
plt.show()


total sales per year := 
 [800001 610002 990003 900004 780005]
year_total  :==
 [ 810000  945000 1085000 1240000]
total sales :==
 4080000
minimum sales per resturent :==
 [150000 120000 200000 180000 160000]
maximum sales per year :==
 [200000 230000 260000 300000]
average sales per restaurent :==
 [200000. 152500. 247500. 225000. 195000.]
average sales per year ;=
 [162000. 189000. 217000. 248000.]
cumulative sales :==
 [[ 150000  180000  220000  250000]
 [ 270000  320000  380000  440000]
 [ 470000  550000  640000  740000]
 [ 650000  760000  880000 1010000]
 [ 810000  945000 1085000 1240000]]


In [ ]:
vecto1 = np.array([1,2,3,4,5])
vecto2 = np.array([6,7,8,9,2])
print("Adition of vector : ",vecto1+vecto2)
print("Adition of multiplication : ",vecto1*vecto2)
print("Adition of dot : ",np.dot(vecto1,vecto2))
angle = np.arccos(np.dot(vecto1,vecto2)/(np.linalg.norm(vecto1)*np.linalg.norm(vecto2)))
print("Angle between vectors : ",np.degrees(angle))

Adition of vector :  [ 7  9 11 13  7]
Adition of multiplication :  [ 6 14 24 36 10]
Adition of dot :  90
Angle between vectors :  37.50230700018765


In [ ]:
restaurant_types = np.array(['veg',"non-veg","italian","rameyan","british","cafe"])
print(restaurant_types)
vectorize_upper = np.vectorize(str.upper)
print("vectorize uperr : ",vectorize_upper(restaurant_types))

['veg' 'non-veg' 'italian' 'rameyan' 'british' 'cafe']
vectorize uperr :  ['VEG' 'NON-VEG' 'ITALIAN' 'RAMEYAN' 'BRITISH' 'CAFE']


In [ ]:
monthly_avg = sales_data[:,1:] /12
print("monthly_avg  :",monthly_avg)

monthly_avg  : [[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]


In [ ]:
array1 = np.array([[1,2,3],[5,6,7]])
array2 = np.random.rand(3,3)
array3 = np.zeros((4,4))

np.save('array1.npy',array1)
np.save('array2.npy',array3)
np.save('array3.npy',array2)

In [ ]:
loaded_array1= np.load('array1.npy')
loaded_array2= np.load('array2.npy')
loaded_array3= np.load('array3.npy')
print(loaded_array1)
print(loaded_array2)
print(loaded_array3)

[[1 2 3]
 [5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.46889192 0.91883914 0.33350618]
 [0.18660402 0.46158156 0.8041863 ]
 [0.25952133 0.02525898 0.92951599]]
